version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      core-go-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /adapters/rod
    schedule:
      interval: weekly
    groups:
      rod-go-dependencies:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /scripts/releaseplan
    schedule:
      interval: weekly
    groups:
      release-tool-go-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
